version: "2"

services:
  acidback:
    container_name: acidback
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.backend=acidback"
      - "traefik.frontend.rule=PathPrefixStrip: /api"
    networks:
      - traefik
networks:
  traefik:
    external:
      name: acidloadb_webgateway
